Update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -287,87 +287,87 @@ jobs:
           cd ../..
           chmod +x test/smoke/smoke-test.sh
           test/smoke/smoke-test.sh http://localhost:3000
-  docker-test:
-    runs-on: ubuntu-latest
-    steps:
-      - name: "Check out Git repository"
-        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
-      - name: "Execute smoke test on Docker"
-        run: docker compose -f docker-compose.test.yml up --exit-code-from sut
-  docker:
-    if: github.repository == 'juice-shop/juice-shop' && github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
-    needs: [test, api-test, e2e, custom-config-test, docker-test]
-    runs-on: ubuntu-latest
-    steps:
-      - name: "Check out Git repository"
-        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
-      - name: "Set up QEMU"
-        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 #v3.0.0
-      - name: "Set up Docker Buildx"
-        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 #v3.0.0
-      - name: "Login to DockerHub"
-        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d #v3.0.0
-        with:
-          username: ${{ secrets.DOCKERHUB_USERNAME }}
-          password: ${{ secrets.DOCKERHUB_TOKEN }}
-      - name: "Set tag & labels for ${{ github.ref }}"
-        run: |
-          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
-          echo "DOCKER_TAG=latest" >> $GITHUB_ENV
-          else
-          echo "DOCKER_TAG=snapshot" >> $GITHUB_ENV
-          fi
-          echo "VCS_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV
-          echo "BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”`" >> $GITHUB_ENV
-      - name: "Build and push for AMD64 and ARM64 processors"
-        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 #v5.1.0
-        with:
-          context: .
-          file: ./Dockerfile
-          platforms: linux/amd64,linux/arm64
-          push: true
-          tags: |
-            bkimminich/juice-shop:${{ env.DOCKER_TAG }}
-          build-args: |
-            VCS_REF=${{ env.VCS_REF }}
-            BUILD_DATE=${{ env.BUILD_DATE }}
-            CYCLONEDX_NPM_VERSION=${{ env.CYCLONEDX_NPM_VERSION }}
-  heroku:
-    if: github.repository == 'juice-shop/juice-shop' && github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
-    needs: [test, api-test, e2e, custom-config-test]
-    runs-on: ubuntu-latest
-    steps:
-      - name: "Check out Git repository"
-        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
-      - name: "Set Heroku app & branch for ${{ github.ref }}"
-        run: |
-          if [ "$GITHUB_REF" == "refs/heads/master" ]; then
-          echo "HEROKU_APP=juice-shop" >> $GITHUB_ENV
-          echo "HEROKU_BRANCH=master" >> $GITHUB_ENV
-          else
-          echo "HEROKU_APP=juice-shop-staging" >> $GITHUB_ENV
-          echo "HEROKU_BRANCH=develop" >> $GITHUB_ENV
-          fi
-      - name: "Deploy ${{ github.ref }} to Heroku"
-        uses: akhileshns/heroku-deploy@9fd0f9faae4aa93a38d6f5e25b9128589f1371b0 #v3.12.14
-        with:
-          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
-          heroku_app_name: ${{ env.HEROKU_APP }}
-          heroku_email: bjoern.kimminich@owasp.org
-          branch: ${{ env.HEROKU_BRANCH }}
-  notify-slack:
-    if: github.repository == 'juice-shop/juice-shop' && github.event_name == 'push' && (success() || failure())
-    needs:
-      - docker
-      - heroku
-      - lint
-      - coding-challenge-rsn
-      - smoke-test
-      - coverage-report
-    runs-on: ubuntu-latest
-    steps:
-      - name: "Slack workflow notification"
-        uses: Gamesight/slack-workflow-status@26a36836c887f260477432e4314ec3490a84f309 #v1.2.0
-        with:
-          repo_token: ${{ secrets.GITHUB_TOKEN }}
-          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
+  #docker-test:
+  #  runs-on: ubuntu-latest
+  #  steps:
+   # - name: "Check out Git repository"
+#         uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
+#       - name: "Execute smoke test on Docker"
+#         run: docker compose -f docker-compose.test.yml up --exit-code-from sut
+#   docker:
+#     if: github.repository == 'juice-shop/juice-shop' && github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
+#     needs: [test, api-test, e2e, custom-config-test, docker-test]
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: "Check out Git repository"
+#         uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
+#       - name: "Set up QEMU"
+#         uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 #v3.0.0
+#       - name: "Set up Docker Buildx"
+#         uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 #v3.0.0
+#       - name: "Login to DockerHub"
+#         uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d #v3.0.0
+#         with:
+#           username: ${{ secrets.DOCKERHUB_USERNAME }}
+#           password: ${{ secrets.DOCKERHUB_TOKEN }}
+#       - name: "Set tag & labels for ${{ github.ref }}"
+#         run: |
+#           if [ "$GITHUB_REF" == "refs/heads/master" ]; then
+#           echo "DOCKER_TAG=latest" >> $GITHUB_ENV
+#           else
+#           echo "DOCKER_TAG=snapshot" >> $GITHUB_ENV
+#           fi
+#           echo "VCS_REF=`git rev-parse --short HEAD`" >> $GITHUB_ENV
+#           echo "BUILD_DATE=`date -u +”%Y-%m-%dT%H:%M:%SZ”`" >> $GITHUB_ENV
+#       - name: "Build and push for AMD64 and ARM64 processors"
+#         uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 #v5.1.0
+#         with:
+#           context: .
+#           file: ./Dockerfile
+#           platforms: linux/amd64,linux/arm64
+#           push: true
+#           tags: |
+#             bkimminich/juice-shop:${{ env.DOCKER_TAG }}
+#           build-args: |
+#             VCS_REF=${{ env.VCS_REF }}
+#             BUILD_DATE=${{ env.BUILD_DATE }}
+#             CYCLONEDX_NPM_VERSION=${{ env.CYCLONEDX_NPM_VERSION }}
+#   heroku:
+#     if: github.repository == 'juice-shop/juice-shop' && github.event_name == 'push' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master')
+#     needs: [test, api-test, e2e, custom-config-test]
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: "Check out Git repository"
+#         uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac #v4.0.0
+#       - name: "Set Heroku app & branch for ${{ github.ref }}"
+#         run: |
+#           if [ "$GITHUB_REF" == "refs/heads/master" ]; then
+#           echo "HEROKU_APP=juice-shop" >> $GITHUB_ENV
+#           echo "HEROKU_BRANCH=master" >> $GITHUB_ENV
+#           else
+#           echo "HEROKU_APP=juice-shop-staging" >> $GITHUB_ENV
+#           echo "HEROKU_BRANCH=develop" >> $GITHUB_ENV
+#           fi
+#       - name: "Deploy ${{ github.ref }} to Heroku"
+#         uses: akhileshns/heroku-deploy@9fd0f9faae4aa93a38d6f5e25b9128589f1371b0 #v3.12.14
+#         with:
+#           heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
+#           heroku_app_name: ${{ env.HEROKU_APP }}
+#           heroku_email: bjoern.kimminich@owasp.org
+#           branch: ${{ env.HEROKU_BRANCH }}
+#   notify-slack:
+#     if: github.repository == 'juice-shop/juice-shop' && github.event_name == 'push' && (success() || failure())
+#     needs:
+#       - docker
+#       - heroku
+#       - lint
+#       - coding-challenge-rsn
+#       - smoke-test
+#       - coverage-report
+#     runs-on: ubuntu-latest
+#     steps:
+#       - name: "Slack workflow notification"
+#         uses: Gamesight/slack-workflow-status@26a36836c887f260477432e4314ec3490a84f309 #v1.2.0
+#         with:
+#           repo_token: ${{ secrets.GITHUB_TOKEN }}
+#           slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
